	%macro string 2
	;mov ecx,%2
	mov eax,4
	mov ebx,1
	mov ecx,%1
	mov edx,%2
	int 0x80
	%endmacro
	
	%macro integer 2
	pusha
	push %1
        push %2
	call printf
        add esp,8
	popa
	%endmacro

       %macro star 2
	mov ecx,%2
abc:
	push ecx
	mov eax,4
	mov ebx,1
	mov ecx,%1
	mov edx,1
	int 0x80
	pop ecx
	loop abc
	%endmacro
;;macro for 10 spc
%macro print1 2
mov ecx,%2

%%abc:push ecx
mov ecx,%1
mov edx,1
mov eax,4
mov ebx,1
int 0x80
pop ecx
loop %%abc
%endmacro